apiVersion: v1
kind: Secret
metadata:
  name: davinci-secrets
  namespace: davinci-backend
type: Opaque
stringData:
  # Database Configuration - Replace with your actual Digital Ocean values
  DATABASE_URL: ""

  # Redis Configuration - Will connect to Redis service in cluster
  REDIS_URL: ""

  # Firebase Configuration - Replace with your actual values
  FIREBASE_PROJECT_ID: ""
  FIREBASE_PRIVATE_KEY: ""
  FIREBASE_CLIENT_EMAIL: ""
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: davinci-config
  namespace: davinci-backend
data:
  NODE_ENV: "production"
  PORT: "3000"
  # Add any non-sensitive configuration here
